losangeleslakers: lakers
lalakers: lakers
goldenstatewarriors: warriors
gswarriors: warriors
bostonceltics: celtics
manchesterunited: manutd
manutd: manutd
manchestercity: mancity
realmadridcf: realmadrid
fcbarcelona: barcelona
