"""Derive Polymarket CLOB API credentials and write .env.

What this does
--------------
1. Prompts (without echo) for your MetaMask private key.
2. Prompts for your Polymarket proxy address (from polymarket.com → Settings).
3. Calls py-clob-client's ``create_or_derive_api_creds()`` which either
   (a) returns the API creds previously bound to this signer, or (b)
   creates a new set deterministically from the signer. Polymarket's
   UI "Relayer API Key" dialog is a different (read-only) credential;
   trading needs the three-field set this script produces.
4. Writes ``.env`` in the project root with all five POLY_* fields,
   chmod 600 (owner-only read/write). Overwrites any existing .env
   after a confirmation prompt.

Why a script, not the UI
------------------------
Polymarket's web Settings page only surfaces a single "Relayer API
Key" + Address pair. The CLOB trading API needs (key, secret,
passphrase) which are produced by EIP-712 signing of a fixed message
against the signer's PK — exactly what py-clob-client does internally.
This script is a thin wrapper so the secret + passphrase never have
to be copy-pasted anywhere.

Secrets policy
--------------
- Private key is read via ``getpass`` — never echoed, never argv.
- .env is written with mode 0600.
- Nothing is printed to stdout except the success message.
- Run on a trusted machine. Anyone who can read .env can drain the
  associated wallet.
"""
from __future__ import annotations

import os
import re
import sys
from getpass import getpass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ENV_PATH = ROOT / ".env"
POLY_CHAIN_ID = 137                  # Polygon mainnet
CLOB_HOST = "https://clob.polymarket.com"


def _prompt_pk() -> str:
    raw = getpass("MetaMask private key (input hidden): ").strip()
    if not raw:
        raise SystemExit("aborted: empty private key")
    if not raw.startswith("0x"):
        raw = "0x" + raw
    if not re.fullmatch(r"0x[0-9a-fA-F]{64}", raw):
        raise SystemExit("aborted: PK is not a 0x-prefixed 64-char hex string")
    return raw


def _prompt_proxy() -> str:
    raw = input("Polymarket proxy address (0x…): ").strip()
    if not re.fullmatch(r"0x[0-9a-fA-F]{40}", raw):
        raise SystemExit("aborted: proxy address is not a 0x-prefixed 40-char hex address")
    return raw


def _derive_creds(pk: str, proxy: str):
    # Lazy import: avoid the multi-second py-clob-client import at file load.
    from py_clob_client.client import ClobClient
    from py_clob_client.clob_types import ApiCreds  # noqa: F401 — kept for type clarity

    client = ClobClient(
        host=CLOB_HOST,
        chain_id=POLY_CHAIN_ID,
        key=pk,
        funder=proxy,
        signature_type=2,            # 2 = POLY_PROXY (Gnosis-safe proxy wallet)
    )
    creds = client.create_or_derive_api_creds()
    return creds.api_key, creds.api_secret, creds.api_passphrase


def _write_env(api_key: str, api_secret: str, api_passphrase: str,
               proxy: str, pk: str) -> None:
    if ENV_PATH.exists():
        ans = input(f".env already exists at {ENV_PATH} — overwrite? [y/N]: ").strip().lower()
        if ans != "y":
            raise SystemExit("aborted: .env not overwritten")
    lines = [
        "# Generated by scripts/init_polymarket_env.py — do not commit.",
        f"POLY_API_KEY={api_key}",
        f"POLY_API_SECRET={api_secret}",
        f"POLY_API_PASSPHRASE={api_passphrase}",
        f"POLY_PROXY_ADDRESS={proxy}",
        f"POLY_FUNDER_PK={pk}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines))
    os.chmod(ENV_PATH, 0o600)


def main() -> int:
    print("Polymarket .env initialiser")
    print("---------------------------")
    print(f"This will write {ENV_PATH} (mode 0600).")
    print("Your PK never leaves this process. The three CLOB credentials are")
    print("derived from your PK by signing an EIP-712 message — no on-chain tx,")
    print("no MATIC cost. Polymarket binds them to your proxy address.\n")
    pk = _prompt_pk()
    proxy = _prompt_proxy()
    print("\nDeriving API credentials from Polymarket CLOB…")
    api_key, api_secret, api_passphrase = _derive_creds(pk, proxy)
    _write_env(api_key, api_secret, api_passphrase, proxy, pk)
    print(f"\nOK  wrote {ENV_PATH} with five POLY_* fields (mode 0600)")
    print("Next: python scripts/live_runner.py --mode live --once --min-edge 5.0")
    print("      (the inflated min-edge guarantees no orders fire during preflight)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
